parameters:
    platform.entity.user.class: Lincode\RestApi\Bundle\Entity\Member
    platform.user.provider.class: Lincode\RestApi\Bundle\Provider\UserProvider
    adoy_oauth2.client.class: OAuth2\Client
    oauth_client.client.class: Lincode\RestApi\Bundle\Service\OAuth2Client

services:
    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_method: getManagerForClass
        factory_service: doctrine
        arguments: ['%platform.entity.user.class%']

    platform.user.repository:
        class: CMS\OAuthServerBundle\Repository\UserRepository
        factory_method: getRepository
        factory_service: platform.user.manager
        arguments: ['%platform.entity.user.class%']

    platform.user.provider:
        class: %platform.user.provider.class%
        arguments: ['@platform.user.repository']

    adoy_oauth2.client:
        class: %adoy_oauth2.client.class%
        arguments: ['%oauth2_client_id%', '%oauth2_client_secret%']

    oauth_client.credentials_client:
        class: %oauth_client.client.class%
        arguments: ['@adoy_oauth2.client', '%oauth2_auth_endpoint%', '%oauth2_token_endpoint%', '%oauth2_redirect_url%', client_credentials, { client_id: '%oauth2_client_id%', client_secret: '%oauth2_client_secret%' }]

    oauth_client.authorize_client:
        class: %oauth_client.client.class%
        arguments: ['@adoy_oauth2.client', '%oauth2_auth_endpoint%', '%oauth2_token_endpoint%', '%oauth2_redirect_url%', authorization_code, { redirect_uri: '%oauth2_redirect_url%' }]

    lincode.user.login_service:
        class: Lincode\RestApi\Bundle\Service\LoginService
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@serializer"]
